name: code

on:
  workflow_dispatch: 

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.version.outputs.go_version }}
          check-latest: true

      - name: code
        run: |
          git clone -b main https://github.com/Mahdi-zarei/nekoray.git nekoray
          cd nekoray/go/cmd/nekobox_core
          awk '{if(index($0, "replace github.com/sagernet/sing-box =>") > 0) $0 = "replace github.com/sagernet/sing-box => ../../../../sing-box"}1' go.mod > temp_file && mv -f temp_file go.mod 
          awk '1; END { print "replace github.com/sagernet/sing => ../../../../sing" }' go.mod > go.mod.tmp && mv -f go.mod.tmp go.mod 
          awk '1; END { print "replace github.com/sagernet/sing-quic => ../../../../sing-quic" }' go.mod > go.mod.tmp && mv -f go.mod.tmp go.mod
          cd ../../../libs
          sed -i 's/with_wireguard/with_wireguard,with_shadowsocksr/g' build_go.sh
          cd ../3rdparty
          rm -rf QHotkey
          curl -L -o QHotkey-52e25acf221e5ac86ce648f6922620fb2d6a7121.zip https://github.com/Skycoder42/QHotkey/archive/52e25acf221e5ac86ce648f6922620fb2d6a7121.zip
          unzip QHotkey-52e25acf221e5ac86ce648f6922620fb2d6a7121.zip
          rm -f QHotkey-52e25acf221e5ac86ce648f6922620fb2d6a7121.zip
          mv QHotkey-52e25acf221e5ac86ce648f6922620fb2d6a7121 QHotkey
          rm -rf qjs
          curl -L -o qjs-3fb0770c9ee5ab031a56072520641d4577b694e3.zip https://github.com/MatsuriDayo/qjs/archive/3fb0770c9ee5ab031a56072520641d4577b694e3.zip
          unzip qjs-3fb0770c9ee5ab031a56072520641d4577b694e3.zip
          rm -f 3fb0770c9ee5ab031a56072520641d4577b694e3.zip
          mv qjs-3fb0770c9ee5ab031a56072520641d4577b694e3 qjs
          cd ../..
          chmod -x .github/edit.sh
          bash .github/edit.sh
          
      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b dev2.2
          rm -rf .github
          rm -f README.md
          cp -r nekoray/* .
          cp -r nekoray/.github .
          rm -rf nekoray
          git add .
          git commit -m "commit"
          git push --force origin dev2.2
